### ISSUE TITLE
magit-gh-pulls on MELPA stable, but gh-pulls is not

### ISSUE THREAD

**Issue by mkleehammer** [sigma/magit-gh-pulls#37]
Using M-x package-install I installed magit-gh-pulls but it failed with (void-variable gh-pulls).

Two things:
1) I notice gh-pulls isn't available on MELPA stable - any help there would be great.
2) Shouldn't the install have failed with a msg about a missing dependency?  Is there a way to specify dependencies and are they up to date?

Thanks

**Comment by alexander-yakushev** [comment]
Good points, but I'm afraid I can't help you with them right now.

1) Do you mean `gh.el`? That package is still managed by @sigma who've lately been out of Emacs-related business. You might want to create an issue here https://github.com/sigma/gh.el and hope it is resolved in some foreseeable future.
2) In the header we have dependencies specified, and I always supposed they just work but I never had any idea how or whether at all. I believe it is described somewhere in ELPA documentation or something.

**Comment by mkleehammer** [comment]
I see what you mean - gh-pull is a file in gh.

It turns out I have gh 0.9.2 but `(require 'gh-pulls)` always fails unless I `(require 'gh)` first.

Do you usually require gh first?  I'm wondering if a `(require 'gh)` should actually be added?

Your dependencies link (thank you for being so thorough) made me realize I am also on a very old version, 0.3.  MEPLA stable (as opposed to regular MELPA) only provides tagged versions.  Could you add a 0.5.2 tag in the meantime?

**Comment by mkleehammer** [comment]
OK, not as clear as I had hoped:

A `(require 'gh-pulls)` fails unless I first `(require gh)`.

_However_, this still fails with "require: Symbol's value as variable is void: gh-pulls"

```elisp
(require 'gh)
(require 'gh-pulls)
(require 'magit-gh-pulls)
```

Any ideas?

**Comment by alexander-yakushev** [comment]
OK, I don't know why the last snippet fails for you, but just in case I changed the order of requires in magit-gh-pulls. Now gh is required before gh-pulls.

I've also put a tag on the last commit so now (soon?) it should be available in melpa stable.

**Comment by mkleehammer** [comment]
That fixed it.  I don't know what the root cause was.  Thanks!

**Comment by alexander-yakushev** [comment]
Great, thanks for reporting!
